# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1250, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btn_Capture = QtGui.QPushButton(self.centralwidget)
        self.btn_Capture.setGeometry(QtCore.QRect(340, 410, 158, 27))
        self.btn_Capture.setObjectName(_fromUtf8("btn_Capture"))
        self.feFrame = QtGui.QFrame(self.centralwidget)
        self.feFrame.setGeometry(QtCore.QRect(20, 10, 390, 390))
        self.feFrame.setFrameShape(QtGui.QFrame.Panel)
        self.feFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.feFrame.setLineWidth(3)
        self.feFrame.setMidLineWidth(0)
        self.feFrame.setObjectName(_fromUtf8("feFrame"))
        self.feLabel = QtGui.QLabel(self.feFrame)
        self.feLabel.setGeometry(QtCore.QRect(10, 10, 370, 370))
        self.feLabel.setText(_fromUtf8(""))
        self.feLabel.setWordWrap(False)
        self.feLabel.setIndent(-1)
        self.feLabel.setObjectName(_fromUtf8("feLabel"))
        self.ptzFrame = QtGui.QFrame(self.centralwidget)
        self.ptzFrame.setGeometry(QtCore.QRect(420, 10, 390, 390))
        self.ptzFrame.setFrameShape(QtGui.QFrame.Panel)
        self.ptzFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.ptzFrame.setLineWidth(3)
        self.ptzFrame.setMidLineWidth(0)
        self.ptzFrame.setObjectName(_fromUtf8("ptzFrame"))
        self.ptzLabel = QtGui.QLabel(self.ptzFrame)
        self.ptzLabel.setGeometry(QtCore.QRect(10, 10, 370, 370))
        self.ptzLabel.setText(_fromUtf8(""))
        self.ptzLabel.setWordWrap(False)
        self.ptzLabel.setIndent(-1)
        self.ptzLabel.setObjectName(_fromUtf8("ptzLabel"))
        self.gb_Absolute = QtGui.QGroupBox(self.centralwidget)
        self.gb_Absolute.setGeometry(QtCore.QRect(960, 90, 171, 191))
        self.gb_Absolute.setAutoFillBackground(False)
        self.gb_Absolute.setObjectName(_fromUtf8("gb_Absolute"))
        self.btn_AbsUp = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsUp.setGeometry(QtCore.QRect(60, 30, 50, 30))
        self.btn_AbsUp.setObjectName(_fromUtf8("btn_AbsUp"))
        self.btn_AbsLeft = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsLeft.setGeometry(QtCore.QRect(20, 60, 50, 30))
        self.btn_AbsLeft.setObjectName(_fromUtf8("btn_AbsLeft"))
        self.btn_AbsRight = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsRight.setGeometry(QtCore.QRect(100, 60, 50, 30))
        self.btn_AbsRight.setObjectName(_fromUtf8("btn_AbsRight"))
        self.btn_AbsDown = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsDown.setGeometry(QtCore.QRect(60, 90, 50, 30))
        self.btn_AbsDown.setObjectName(_fromUtf8("btn_AbsDown"))
        self.btn_AbsZoomOut = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsZoomOut.setGeometry(QtCore.QRect(90, 140, 75, 30))
        self.btn_AbsZoomOut.setObjectName(_fromUtf8("btn_AbsZoomOut"))
        self.btn_AbsZoomIn = QtGui.QPushButton(self.gb_Absolute)
        self.btn_AbsZoomIn.setGeometry(QtCore.QRect(10, 140, 75, 30))
        self.btn_AbsZoomIn.setObjectName(_fromUtf8("btn_AbsZoomIn"))
        self.gb_Continuous = QtGui.QGroupBox(self.centralwidget)
        self.gb_Continuous.setGeometry(QtCore.QRect(950, 300, 171, 181))
        self.gb_Continuous.setFlat(False)
        self.gb_Continuous.setCheckable(False)
        self.gb_Continuous.setObjectName(_fromUtf8("gb_Continuous"))
        self.btn_ContUp = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContUp.setGeometry(QtCore.QRect(60, 30, 50, 30))
        self.btn_ContUp.setObjectName(_fromUtf8("btn_ContUp"))
        self.btn_ContLeft = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContLeft.setGeometry(QtCore.QRect(20, 60, 50, 30))
        self.btn_ContLeft.setObjectName(_fromUtf8("btn_ContLeft"))
        self.btn_ContRight = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContRight.setGeometry(QtCore.QRect(100, 60, 50, 30))
        self.btn_ContRight.setObjectName(_fromUtf8("btn_ContRight"))
        self.btn_ContDown = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContDown.setGeometry(QtCore.QRect(60, 90, 50, 30))
        self.btn_ContDown.setObjectName(_fromUtf8("btn_ContDown"))
        self.btn_ContZoomOut = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContZoomOut.setGeometry(QtCore.QRect(90, 130, 75, 30))
        self.btn_ContZoomOut.setObjectName(_fromUtf8("btn_ContZoomOut"))
        self.btn_ContZoomIn = QtGui.QPushButton(self.gb_Continuous)
        self.btn_ContZoomIn.setGeometry(QtCore.QRect(10, 130, 75, 30))
        self.btn_ContZoomIn.setObjectName(_fromUtf8("btn_ContZoomIn"))
        self.btn_RecVideoFE = QtGui.QPushButton(self.centralwidget)
        self.btn_RecVideoFE.setGeometry(QtCore.QRect(250, 450, 158, 27))
        self.btn_RecVideoFE.setObjectName(_fromUtf8("btn_RecVideoFE"))
        self.btn_RecVideoPTZ = QtGui.QPushButton(self.centralwidget)
        self.btn_RecVideoPTZ.setGeometry(QtCore.QRect(420, 450, 158, 27))
        self.btn_RecVideoPTZ.setObjectName(_fromUtf8("btn_RecVideoPTZ"))
        self.gb_Home = QtGui.QGroupBox(self.centralwidget)
        self.gb_Home.setGeometry(QtCore.QRect(960, 10, 171, 71))
        self.gb_Home.setObjectName(_fromUtf8("gb_Home"))
        self.btn_GotoHome = QtGui.QPushButton(self.gb_Home)
        self.btn_GotoHome.setGeometry(QtCore.QRect(20, 30, 50, 30))
        self.btn_GotoHome.setObjectName(_fromUtf8("btn_GotoHome"))
        self.btn_SetHome = QtGui.QPushButton(self.gb_Home)
        self.btn_SetHome.setGeometry(QtCore.QRect(100, 30, 50, 30))
        self.btn_SetHome.setObjectName(_fromUtf8("btn_SetHome"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Principal", None))
        self.btn_Capture.setText(_translate("MainWindow", "Capturar", None))
        self.gb_Absolute.setTitle(_translate("MainWindow", "Movimiento por paso", None))
        self.btn_AbsUp.setText(_translate("MainWindow", "Arriba", None))
        self.btn_AbsLeft.setText(_translate("MainWindow", "Izq", None))
        self.btn_AbsRight.setText(_translate("MainWindow", "Der", None))
        self.btn_AbsDown.setText(_translate("MainWindow", "Abajo", None))
        self.btn_AbsZoomOut.setText(_translate("MainWindow", "Zoom Out", None))
        self.btn_AbsZoomIn.setText(_translate("MainWindow", "Zoom In", None))
        self.gb_Continuous.setTitle(_translate("MainWindow", "Movimiento continuo", None))
        self.btn_ContUp.setText(_translate("MainWindow", "Arriba", None))
        self.btn_ContLeft.setText(_translate("MainWindow", "Izq", None))
        self.btn_ContRight.setText(_translate("MainWindow", "Der", None))
        self.btn_ContDown.setText(_translate("MainWindow", "Abajo", None))
        self.btn_ContZoomOut.setText(_translate("MainWindow", "Zoom Out", None))
        self.btn_ContZoomIn.setText(_translate("MainWindow", "Zoom In", None))
        self.btn_RecVideoFE.setText(_translate("MainWindow", "Grabar de Fisheye", None))
        self.btn_RecVideoPTZ.setText(_translate("MainWindow", "Grabar de PTZ", None))
        self.gb_Home.setTitle(_translate("MainWindow", "Home", None))
        self.btn_GotoHome.setText(_translate("MainWindow", "Ir", None))
        self.btn_SetHome.setText(_translate("MainWindow", "Set", None))

